name: Executar Testes Cypress

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Cypress e dependências
        uses: cypress-io/github-action@v5
        with:
          runTests: false # Evita execução automática

      - name: Executar todos os testes Cypress
        run: |
          echo "Iniciando execução de todos os arquivos de teste .cy.js"
          npx cypress run --spec "cypress/e2e/**/*.cy.js"
